In [9]:
import json
from kafka import KafkaProducer
import pandas as pd
from time import time

In [5]:
def json_serializer(data):
    return json.dumps(data).encode('utf-8')

server = 'localhost:9092'

producer = KafkaProducer(
    bootstrap_servers=[server],
    value_serializer=json_serializer
)

producer.bootstrap_connected()

True

In [7]:
# Read data
df = pd.read_csv("green_tripdata_2019-10.csv")
cols = [
    'lpep_pickup_datetime',
    'lpep_dropoff_datetime',
    'PULocationID',
    'DOLocationID',
    'passenger_count',
    'trip_distance',
    'tip_amount'
]
df = df[cols]
df.head(10)

/tmp/ipykernel_54488/2717073636.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("green_tripdata_2019-10.csv")

,lpep_pickup_datetime,lpep_dropoff_datetime,PULocationID,DOLocationID,passenger_count,trip_distance,tip_amount
0,2019-10-01 00:26:02,2019-10-01 00:39:58,112,196,1.0,5.88,0.00
1,2019-10-01 00:18:11,2019-10-01 00:22:38,43,263,1.0,0.80,0.00
2,2019-10-01 00:09:31,2019-10-01 00:24:47,255,228,2.0,7.50,0.00
3,2019-10-01 00:37:40,2019-10-01 00:41:49,181,181,1.0,0.90,0.00
4,2019-10-01 00:08:13,2019-10-01 00:17:56,97,188,1.0,2.52,2.26
5,2019-10-01 00:35:01,2019-10-01 00:43:40,65,49,1.0,1.47,1.86
6,2019-10-01 00:28:09,2019-10-01 00:30:49,7,179,1.0,0.60,1.00
7,2019-10-01 00:28:26,2019-10-01 00:32:01,41,74,1.0,0.56,0.00
8,2019-10-01 00:14:01,2019-10-01 00:26:16,255,49,1.0,2.42,0.00
9,2019-10-01 00:03:03,2019-10-01 00:17:13,130,131,1.0,3.40,2.85

In [11]:
# Send messages

t0 = time()

for _, row in df.iterrows():
    message = row.to_dict()
    producer.send("green_trips", value=message)

producer.flush()

t1 = time()
took = t1 - t0

print(f"Time taken to send and flush: {took:.2f} seconds")

Time taken to send and flush: 71.52 seconds